[project]
name = "renovate-repro-uv-git-deps"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "django-types",
]

[tool.uv.sources.django-types]
git = "https://github.com/sbdchd/django-types"
rev = "145e9dfc496f8b4536b7334b5c6d69c29a44252f"
